### ISSUE TITLE
Update everything to latest sbt, scala, scalaz.

### ISSUE THREAD

**Issue by markhibberd** [ambiata/introduction-to-fp-in-scala#10]

**Comment by tmcgilchrist** [comment]
Is this just a matter of bumping everything to the latest and fixing what breaks? @markhibberd

**Comment by markhibberd** [comment]
@tmcgilchrist Yeh pretty much. The basic stack for us is, sbt 0.13.7, scala 2.11.5,  scalaz 7.10, specs2 2.4.5, and scalcheck 1.11 (whatever specs happens to pull in, can't remember off the top of my head).

**Comment by tmcgilchrist** [comment]
This this can probably be crossed of the TODO list now @markhibberd ?

**Comment by charleso** [comment]
I think it can. Thanks again @tmcgilchrist.
